### ISSUE TITLE
Get List Of Words sorted by frequency

### ISSUE THREAD

**Issue by Ksushik** [WordsAPI/wordfrequencies#1]
Hello. it would be nice to have a parameter to get words (by lengnh or pattern) sorted by frequency.
Do you have such?
Also it could be usefull to return number of pages when result size more than 100

Thank's ahead)

**Comment by johntitus** [comment]
Hi, 
Seems like good idea, but I believe you're asking about the WordsAPI API, and not this open source package?

I'll add it to our to-do list for the API.
